### ISSUE TITLE
Not able to download drcsim, hector_gazebo, gazebo_ros_pkgs

### ISSUE THREAD

**Issue by shubham9436** [ldgcug/erlecopter_gazebo8#11]
How to download these three packages?
I am not able to sign up as I don't have Chinese phone number.

Can you upload somewhere else where it is available for outside China?

**Comment by wqhcug** [comment]
I have sent the three files to your mail.
Please look for the  Mail attachment.


Good Luck.


------------------ 原始邮件 ------------------
发件人: "Shubham Baranwal"<notifications@github.com>;
发送时间: 2019年9月21日(星期六) 下午4:18
收件人: "ldgcug/erlecopter_gazebo8"<erlecopter_gazebo8@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ldgcug/erlecopter_gazebo8] Not able to download drcsim,hector_gazebo, gazebo_ros_pkgs (#11)




How to download these three packages?
 I am not able to sign up as I don't have Chinese phone number.
 
Can you upload somewhere else where it is available for outside China?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

3 file.zip (340.81M, 2019年10月22日 08:56 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0e623437d36b87d2ee08e71247630617040455010451075b1c500504074e000f5257190f59540d1507500306565a075b010403076169340b11045d5b044d4e51416209&code=1b47ac48




readme.md (90B, 2019年09月22日 09:01 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0b363237c3cecf9bea5ce1124331024b045354030455530018040253041c045d0c571f0e5506514902570a005153525405010b06653830165057565a001f5d00350b&code=5627e10d

**Comment by shubham9436** [comment]
Thanks a lot. I was struggling for the past two days for these files.

Regards,
Shubham
